export class Teams
{
    teamProductDemandId:number
    teamId:number
    teamName:string 
    establishmentDate:Date
    numberOfMembers:number
    teamWorkType:number
    teamMail:string
    teamPhone:string 
    advisorId:number
    quantity:number
    quantityPrice:number
    totalPrice:number
    affiliatedInstitutionId:number
    isDeleted:number
    transactionType:number
    systemDate:Date
    updateSystemDate:Date
}